version: "3.7"

services:
  user_pg:
    image: postgres
    container_name: user_pg
    restart: always
    environment:
      POSTGRES_USER: userdb
      POSTGRES_HOST: localhost
      POSTGRES_PASSWORD: userdb
      POSTGRES_DATABASE: userdb
    ports:
      - 5432:5432
