version: "3"
services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: pgdb
      POSTGRES_HOST: localhost
      POSTGRES_PASSWORD: pgdb
      POSTGRES_DA TABASE: pgdb
    ports:
      - 5433:5432
