version: "3"
services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: pgdb
      POSTGRES_HOST: localhost
      POSTGRES_PASSWORD: pgdb
      POSTGRES_DATABASE: pgdb
    ports:
      - 5433:5432
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
